### ISSUE TITLE
NullPointer when executing drawRadial

### ISSUE THREAD

**Issue by pierrejego** [LETG/coastlinetracking#7]
Problem avec la line de référence qui n'est pas vu comme une lineString 

Apr 09:44:01 DEBUG [geoserver.requests] - Query is org.geoserver.wfs.request.Query$WFS11@2df1a4d3
 To gt2: Query:
   feature type: REF1_VOUGOT
   filter: Filter.INCLUDE
   [properties:  ALL ]
19 Apr 09:44:01 DEBUG [feature.simple] - Creating geometry with null CoordinateReferenceSystem - did you mean to setCRS?
19 Apr 09:44:01 DEBUG [geotools.jdbc] - CREATE CONNECTION
19 Apr 09:44:01 DEBUG [geotools.jdbc] - SELECT "id",encode(ST_AsEWKB("geom"), 'base64') as "geom","x","y","z","identifiant","date" FROM "vougot"."REF1_VOUGOT" LIMIT 1000000
19 Apr 09:44:01 ERROR [utils.WPSUtils] - Error while executing getReferenceLineFromFeature
java.lang.Exception: la geometrie n'est pas une LineString !
        at fr.indigeo.wps.clt.utils.WPSUtils.getReferenceLineFromFeature(WPSUtils.java:114)
        at fr.indigeo.wps.clt.CoastLinesTrackingWPS.drawRadial(CoastLinesTrackingWPS.java:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:622)
        at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:223)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:191)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
19 Apr 09:44:01 DEBUG [geotools.jdbc] - CLOSE CONNECTION

Il faut revoir la gestion des erreurs pour permettre de débugger en cas de mauvais input

**Comment by pierrejego** [comment]
Le même test avec un JSon LineString en input fonctionne

**Comment by pierrejego** [comment]
link to #11
